name: Run Python Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-15-large

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Source environment and run tests
        run: |
          python3 -m venv venv
          source ./environment.sh
          python3 run_tests.py

